name: Run E2E Tests

on:
  schedule:
    - cron: "0 */12 * * *"  # Every 12 hours
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest  # Keep this as the host, but use a container

    container: python:3.12-slim  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y \
        wget \
        unzip \
        gnupg \
        libglib2.0-0 \
        libnss3 \
        libatk1.0-0 \
        libatk-bridge2.0-0 \
        libcups2 \
        libdrm2 \
        libxkbcommon0 \
        libxcomposite1 \
        libxdamage1 \
        libxfixes3 \
        libxrandr2 \
        libgbm1 \
        libasound2 \
        libpango-1.0-0 \
        libcairo2 \
        && rm -rf /var/lib/apt/lists/*
      
    - name: Download and install Chrome
      run: |
        wget https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/linux64/chrome-linux64.zip && \
        unzip chrome-linux64.zip -d /opt && \
        rm chrome-linux64.zip && \
        ln -s /opt/chrome-linux64/chrome /usr/local/bin/chrome
    
    - name: Download and install ChromeDriver
      run: |
        wget https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/linux64/chromedriver-linux64.zip && \
        unzip chromedriver-linux64.zip -d /opt && \
        rm chromedriver-linux64.zip && \
        ln -s /opt/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver

    - name: Verify installations
      run: chrome --version && chromedriver --version
        
    - name: Install Poetry
      run: |
        pip install poetry \
        && poetry config virtualenvs.create false 
    
    - name: Install poetry dependencies
      run: |
        poetry install
      working-directory: zoom_bot

    - name: Run E2E Tests
      run: |
        poetry run pytest src/zoom_bot/test.py
      working-directory: zoom_bot
