name: Run E2E Tests

on:
  schedule:
    # Run every 12 hours
    - cron: "0 */12 * * *"  # Cron syntax for every 12 hours

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.3  # Specify your Python version here
    
    
    # Step 4: Install Poetry using pipx
    - name: Set up Poetry
      run: |
        pip install poetry \
        && poetry config virtualenvs.create false 
      env:
        VENV_PATH: ${{ github.workspace }}/.venv
      working-directory: zoom_bot
    
    # Step 5: Install dependencies with Poetry
    - name: Install dependencies
      run: |
        poetry install
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        echo "/usr/lib/chromium-browser/chromedriver" > /usr/bin/chromedriver

      working-directory: zoom_bot

    # Step 6: Run the tests with pytest
    - name: Run E2E Tests
      run: |
        poetry run pytest tests/e2e/test_css_selectors.py
      working-directory: zoom_bot
