name: Run E2E Tests

on:
  schedule:
    # Run every 12 hours
    - cron: "0 */12 * * *"  # Cron syntax for every 12 hours

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.3  # Specify your Python version here

    # Step 3: Install Poetry
    - name: Set up Poetry
      run: |
        python3 -m venv $VENV_PATH
        $VENV_PATH/bin/pip install -U pip setuptools
        $VENV_PATH/bin/pip install poetry
      env:
        VENV_PATH: ${{ github.workspace }}/.venv
    # Step 4: Install dependencies with Poetry
    - name: Install dependencies
      run: |
        poetry install  
    # Step 5: Run the tests with pytest
    - name: Run E2E Tests
      run: |
        poetry run pytest tests/e2e/test_css_selectors.py
      working-directory: zoom_bot/zoom_bot
